spring:
  application:
    name: zevin-spring-mvc

server:
  port: 18080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
